POST http://127.0.0.1:3000/auth/register
Content-Type: application/json

{
    "name": "Alexis Coronel",
    "email": "coronel@yavi.com",
    "password": "2321456"
}

### login sin conexion a DB 
POST http://127.0.0.1:3000/auth/login
Content-Type: application/json

{
    "name": "Alexis Coronel",
    "email": "coronel@yavi.com",
    "password": "2321456"
}

### users
GET http://127.0.0.1:3000/users




    